### ISSUE TITLE
'CameraManager' object has no attribute 'get_builder'

### ISSUE THREAD

**Issue by 1bildung** [manuq/stopmo_preview#5]
Hi,
thanks for your great plugin!
I have some trouble to start it:

```
traceback (most recent call last):
File "/home/username/.config/entangle/plugins/stopmo_preview/stopmo_preview.py", line 298, in <lambda>
    lambda app, win: self.do_deactivate_window(win))

File "/home/username/.config/entangle/plugins/stopmo_preview/stopmo_preview.py", line 283, in do_deactivate_window
    w.deactivate()

File "/home/username/.config/entangle/plugins/stopmo_preview/stopmo_preview.py", line 203, in deactivate
    builder = self.win.get_builder()

AttributeError: 'CameraManager' object has no attribute 'get_builder'
```

===

Who owns the 'get_builder' method? I have no idea where I have to look for.

Have a good time!
M.

**Comment by manuq** [comment]
Hello, sorry for the late reply!

It's been years since I don't try this plugin. It seems the UI in Entangle has changed, and the plugin needs to be adapted. See [this commit](https://gitlab.com/entangle/entangle/-/commit/69e430d0f671d95e68f641d073fa4d1171cb0b1a) as reference, which updates the Photo Box plugin.

I will try to update this soon.

**Comment by manuq** [comment]
Closing in favour of #8
